### ISSUE TITLE
Startup-Error

### ISSUE THREAD

**Issue by Ceddix** [CraftTogetherMC/TC-Destinations#2]
Neben dem Fehler, den ich bereits unter CTCommons reportet habe (siehe https://github.com/CraftTogetherMC/CT-Commons/issues/1) schießt TCDestinations eine zweite Fehlermeldung beim Serverstart aus, siehe: https://pastebin.com/j8wYe2fa

**Comment by J0schlZ** [comment]
Fixed. (Please Update CT-Commons)
