### ISSUE TITLE
Clickable Messages not Working

### ISSUE THREAD

**Issue by Ceddix** [CraftTogetherMC/TC-Destinations#3]
Ich weiß nicht, ob das an TCDestinations oder TCCommons liegt, aber in den 1.20er Versionen funktionieren die Klick-Actions in den `/fahrziel`-Befehlen nicht mehr. Also egal wohin man klickt, es passiert nichts.

**Comment by J0schlZ** [comment]
Fixed. (Please update CT-Commons)
