### ISSUE TITLE
`{destinationInformation}` for enter message

### ISSUE THREAD

**Issue by Ceddix** [CraftTogetherMC/TC-Destinations#4]
Im ursprünglichen CraftBahn Plugin wurde mit dem `{destinationInformation}` Placeholder das ausgewählte Fahrziel in der enter message eines Zuges angezeigt, wenn eine gesetzt wurde.

Das sah dann in der Config glaube ich so aus:
```
  craftbahn:  |
    <header/>

    <hover:show_text:'<green>Informationen zum Schienennetz</green>'><click:run_command:/bahnhof><prefix/><yellow>Guten Tag, Reisender!</yellow>
    <prefix/><yellow>Verstehst du nur </yellow>
    <prefix/><red>/bahnhof</red><yellow>?</yellow></click></hover>
    <prefix/>
    {destinationInfo}

    <footer/>
```

Dieses Feature scheint in TCDestinations nicht zu existieren bzw. nicht zu funktionieren.

**Comment by J0schlZ** [comment]
Sollte nun funktionieren, wenn du `{destination}` benutzt.
Außerdem verfügbar: `{trainName}`, `{displayName}`, `{speedLimit}`

**Comment by Ceddix** [comment]
Dankeee 🫶🏼 Werde ich mir morgen mal anschauen 😄

**Comment by Ceddix** [comment]
Das ist aber jetzt *nur* ein Placeholder mit dem Namen der Destination, richtig? Was wird angezeigt, wenn der Zug kein Fahrziel hat?

Im ursprünglichen CraftBahn Plugin gab es zwei verschiedene Nachrichten, die angezeigt wurden, abgängig davon, ob der Zug eine Destination hatte, oder nicht.

Siehe (CraftBahn – TrainEnterListener): https://github.com/CraftTogetherMC/CraftBahn/blob/b02b2d475b8213db5e0364a938e5c2a7068e538a/src/main/java/de/crafttogether/craftbahn/listener/TrainEnterListener.java#L26-L30

Und (CraftBahn – Localization): https://github.com/CraftTogetherMC/CraftBahn/blob/master/src/main/java/de/crafttogether/craftbahn/Localization.java#L17-L29

Im letzten sieht man, wenn der Zug keine Destination hatte, wurde "*Dieser Zug hat noch kein Fahrziel*" sowie ein Hinweis auf `/fahrziele` angezeigt.
Nur wenn der Zug ein Fahrziel hatte, wurde die Nachricht "*Dieser Zug versucht das Ziel `{destination}` zu erreichen.*" angezeigt.

**Comment by J0schlZ** [comment]
Darüber hatte ich auch nachgedacht.
Die Frage ist wie sich das am sinnvollsten umsetzen lässt in der enterMessages.yml

Ich überlege gerade ob es nicht sinnvoll ist placeholder anzulegen, welche die anderen hinterlegten enterMessages repräsentieren.

Oder soll ich gar eine Möglichkeit zum erzeugen von if-bedingungen einbauen?

Ich möchte das so flexibel wie möglich halten von Seiten der Konfiguration.

**Comment by Ceddix** [comment]
If-Bedingungen wäre ziemlich crazy hahah Aber wahrscheinlich auch echt kompliziert, oder?

**Comment by Ceddix** [comment]
Wurde in Commit https://github.com/CraftTogetherMC/TC-Destinations/commit/62871e21ae006957ef9f1a1724088401e5fe522a eingefügt.

Yes, hab's gerade ausgetestet und scheint super zu funktionieren. Danke 😄
